title: Kariel Portfolio
logo: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.instagram.com%2Fgarciajoshuae%2F&psig=AOvVaw1yi8vy8-yJTiob_2elGGV5&ust=1741181182757000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCODhj8HD8IsDFQAAAAAdAAAAABAE
show_download: true
#theme: jekyll-theme-leap-day
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to plugins list if you already have one
#remote_theme: pages-themes/architect@c0.2.0
#plugins:
#- jekyll-jekyll-remote-theme # add this line to plugins list if you already have one
