title: Kariel Portfolio
logo: https://lh3.googleusercontent.com/a/ACg8ocLnVCyQb1oxZd3IPsrOAUkXJYnafCAMSkzAqu4O7r1Fgigbr34=s288-c-no
show_download: true
#theme: jekyll-theme-leap-day
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to plugins list if you already have one
