title: Kariel Portfolio
logo: images/pic.jpg
show_download: true
#theme: jekyll-theme-leap-day
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to plugins list if you already have one

