title: Kariel Portfolio
logo: image/kariel.png
show_download: true
#theme: jekyll-theme-leap-day
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to plugins list if you already have one
#remote_theme: pages-themes/architect@c0.2.0
#plugins:
#- jekyll-jekyll-remote-theme # add this line to plugins list if you already have one
