<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Portfolio</title>
    <style>
        /* Add some basic styles */
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            background-color: #f0f0f0;
        }
        .logo {
            width: 200px; /* Adjust the size as needed */
        }
    </style>
</head>
<body>
    <div>
        <img src="path/to/your/logo.png" alt="My Logo" class="logo">
        <h1>Welcome to My Portfolio</h1>
    </div>
</body>
</html>
